### ISSUE TITLE
可以支持调度每个worker节点的固定路径吗？

### ISSUE THREAD

**Issue by op-family** [caoyingjunz/csi-driver-localstorage#214]
比如我有6个worker节点，每个节点的/data/pixiui  这个路径都被我挂载了200G的盘，我想pixiu-localstorage可以管理这个六个路径，并尽量达到负载均衡

**Comment by mdsq1** [comment]
1、支持指定节点：在对应的worker中执行 `kubectl  label node <node-name> storage.caoyingjunz.io/node=`
2、支持固定路径：ls-node.yaml这个文件中，搜索--volume-dir,将此处的data更换为/data/pixiu即可。           
3、根据容量做调度，还在开发中，预计本周末上；
