### ISSUE TITLE
ls部署成功后，提供初始化job，完成localstorage的自动创建

### ISSUE THREAD

**Issue by caoyingjunz** [caoyingjunz/csi-driver-localstorage#240]
**What's it about?**

**What's the reason why we need it?**

I believe this is an important feature for Pixiu. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by caoyingjunz** [comment]
创建工具函数 https://github.com/caoyingjunz/csi-driver-localstorage/blob/master/pkg/util/storage/storage.go#L77

**Comment by houwenchen** [comment]
whou接
