### ISSUE TITLE
storage-manager health check should be completed

### ISSUE THREAD

**Issue by caoyingjunz** [caoyingjunz/csi-driver-localstorage#7]

**Comment by caoyingjunz** [comment]
done with https://github.com/caoyingjunz/pixiu/commit/4ccfb513689e650858b0b4041858f8877e4d6a98

**Comment by houwenchen** [comment]
whou---接

**Comment by houwenchen** [comment]
https://github.com/caoyingjunz/csi-driver-localstorage/pull/135/commits

**Comment by houwenchen** [comment]
https://github.com/caoyingjunz/csi-driver-localstorage/pull/141
